matching_groups:
  - /user
  - /login
  - /user/[^\/]+/gacha/
  - /user/[^\/]+/gacha/draw
  - /user/[^\/]+/present
  - /user/[^\/]+/item
  - /user/[^\/]+/card
  - /user/[^\/]+/reward
  - /user/[^\/]+/home
  - /admin/login
  - /admin/logout
  - /admin/master
  - /admin/user/[^\/]
sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
  
file: /var/log/nginx/access.ndjson
